export const FILLING_SERIES = 'FILLING_SERIES';
export const FILLING_COUNTRY = 'FILLING_COUNTRY';
export const FILLING_YEAR = 'FILLING_YEAR';

export const CLEANING_SERIES = 'CLEANING_SERIES';
export const CLEANING_COUNTRY = 'CLEANING_COUNTRY';
export const CLEANING_YEAR = 'CLEANING_YEAR';

export const UPDATE_ROWDATA = 'UPDATE_ROWDATA';